trigger:
  - main

pool:
  name: 'Azure Pipelines'

variables:
  tag: '$(Build.BuildId)'

steps:
  - checkout: self
    displayName: 'Checkout GitHub Repository'
    # Build Frontend Docker Image
  - task: Docker@2
    inputs:
      command: build
      dockerfile: src/frontend/Dockerfile
      buildContext: src/frontend
      tags: |
        frontend:$(tag)

  # Trivy@2 Scan Frontend Image
  - task: trivy@2
    continueOnError: true
    inputs:
      version: 'latest'
      type: 'image'
      target: 'frontend:$(tag)'
      severities: 'HIGH, CRITICAL'
      publish: true

  # Build Backend Docker Image
  - task: Docker@2
    inputs:
      command: build
      dockerfile: src/backend/Dockerfile
      buildContext: src/backend
      tags: |
        backend:$(tag)

  # Trivy@2 Scan Backend Image
  - task: trivy@2
    continueOnError: true
    inputs:
      version: 'latest'
      type: 'image'
      target: 'backend:$(tag)'
      severities: 'HIGH, CRITICAL'
      publish: true

