trigger:
  - main

pool:
  name: 'Azure Pipelines'

variables:
- group: sd5184
- name: tag
  value: '$(Build.BuildId)'

steps:
- checkout: self
  displayName: 'Checkout GitHub Repository'

# Build Frontend Image
- task: Docker@2
  inputs:
    command: build
    dockerfile: src/frontend/Dockerfile
    buildContext: src/frontend
    arguments: '--tag demosd5184s.azurecr.io/frontend:$(tag) --tag demosd5184s.azurecr.io/frontend:latest'

# Scan Frontend Image
- task: trivy@2
  continueOnError: true
  inputs:
    version: 'latest'
    type: 'image'
    target: 'demosd5184s.azurecr.io/frontend:$(tag)'
    severities: 'HIGH, CRITICAL'
    publish: true

# Build Backend Image
- task: Docker@2
  inputs:
    command: build
    dockerfile: src/backend/Dockerfile
    buildContext: src/backend
    arguments: '--tag demosd5184s.azurecr.io/backend:$(tag) --tag demosd5184s.azurecr.io/backend:latest'

# Scan Backend Image
- task: trivy@2
  continueOnError: true
  inputs:
    version: 'latest'
    type: 'image'
    target: 'demosd5184s.azurecr.io/backend:$(tag)'
    severities: 'HIGH, CRITICAL'
    publish: true

# Login to ACR
- script: docker login -u sd5184 -p '$(dockerRegistryPassword)' demosd5184s.azurecr.io
  displayName: 'Docker Login to ACR'

# Push Frontend Image
- script: |
    docker push demosd5184s.azurecr.io/frontend:$(tag)
    docker push demosd5184s.azurecr.io/frontend:latest
  displayName: 'Push Frontend Image'

# Push Backend Image
- script: |
    docker push demosd5184s.azurecr.io/backend:$(tag)
    docker push demosd5184s.azurecr.io/backend:latest
  displayName: 'Push Backend Image'
