trigger:
  - main

pool:
  name: 'Azure Pipelines'

variables:
- group: sd5184
- name: tag
  value: '$(Build.BuildId)'

steps:
- checkout: self
  displayName: 'Checkout GitHub Repository'

- task: Docker@2
  inputs:
    command: build
    dockerfile: src/frontend/Dockerfile
    buildContext: src/frontend
    tags: |
      demosd5184s.azurecr.io/frontend:$(tag)

- task: trivy@2
  continueOnError: true
  inputs:
    version: 'latest'
    type: 'image'
    target: 'demosd5184s.azurecr.io/frontend:$(tag)'
    severities: 'HIGH, CRITICAL'
    publish: true

- task: Docker@2
  inputs:
    command: build
    dockerfile: src/backend/Dockerfile
    buildContext: src/backend
    tags: |
      demosd5184s.azurecr.io/backend:$(tag)

- task: trivy@2
  continueOnError: true
  inputs:
    version: 'latest'
    type: 'image'
    target: 'demosd5184s.azurecr.io/backend:$(tag)'
    severities: 'HIGH, CRITICAL'
    publish: true

- script: docker login -u sd5184 -p '$(dockerRegistryPassword)' demosd5184s.azurecr.io
- task: Docker@2
  inputs:
    command: push
    repository: 'demosd5184s.azurecr.io/frontend'
    tags: |
      $(tag)

- task: Docker@2
  inputs:
    command: push
    repository: 'demosd5184s.azurecr.io/backend'
    tags: |
      $(tag)
